version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - comic-directory:/comic-dir
#    environment:
#      DEMOFOLDER: "./node_modules"
volumes:
  comic-directory:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/fotos/Beispiele